import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { env } from '../env.js';
import { logger } from '../logger.js';
import { tooLarge } from '../errors.js';

/**
 * Blob storage.
 *
 * Two rules make path traversal structurally impossible here rather than
 * merely filtered:
 *
 *  1. A storage key is generated by *this module* from a CSPRNG. No part of
 *     any client-supplied string — filename, mime type, id — ever reaches a
 *     path segment.
 *  2. Every resolved path is checked to be inside the storage root before it
 *     is opened, so even a future bug that let a key through would not escape.
 *
 * The bytes stored are always already encrypted by the client. The server
 * holds no key that opens them.
 */

const KEY_PATTERN = /^[0-9a-f]{2}\/[0-9a-f]{2}\/[0-9a-f]{56}$/;

export function newStorageKey(): string {
  const hex = crypto.randomBytes(30).toString('hex'); // 60 hex chars
  // Two levels of fan-out keeps directory sizes reasonable at scale.
  return `${hex.slice(0, 2)}/${hex.slice(2, 4)}/${hex.slice(4)}`;
}

function resolveSafe(storageKey: string): string {
  if (!KEY_PATTERN.test(storageKey)) {
    throw new Error('Refusing to resolve a malformed storage key');
  }
  const root = env.storageRoot;
  const resolved = path.resolve(root, storageKey);
  const rootWithSep = root.endsWith(path.sep) ? root : root + path.sep;
  if (!resolved.startsWith(rootWithSep)) {
    throw new Error('Resolved storage path escaped the storage root');
  }
  return resolved;
}

export async function ensureStorageReady(): Promise<void> {
  await fsp.mkdir(env.storageRoot, { recursive: true, mode: 0o700 });
  logger.info({ path: env.storageRoot }, 'blob storage ready');
}

export interface StoredBlob {
  storageKey: string;
  size: number;
  /** SHA-256 of the stored ciphertext. */
  hash: Uint8Array;
}

/**
 * Stream a blob to disk, enforcing the size cap as bytes arrive rather than
 * after the fact — a 10 GB upload must be refused mid-flight, not buffered.
 */
export async function writeBlob(
  source: Readable,
  maxBytes: number,
): Promise<StoredBlob> {
  const storageKey = newStorageKey();
  const target = resolveSafe(storageKey);
  await fsp.mkdir(path.dirname(target), { recursive: true, mode: 0o700 });

  const hasher = crypto.createHash('sha256');
  let size = 0;

  /*
   * Boxed rather than a bare `let`. The handlers below are the only writers,
   * and TypeScript narrows a `let` that is only ever assigned inside a closure
   * down to its initialiser — so `throw aborted` would be a throw of `never`.
   * A property is re-read at each use and narrows honestly.
   */
  const failed: { error: Error | null } = { error: null };

  const counter = new Readable({ read() {} });

  source.on('data', (chunk: Buffer) => {
    if (failed.error) return;
    size += chunk.length;
    if (size > maxBytes) {
      const err = tooLarge('That file is larger than the allowed limit');
      failed.error = err;
      source.destroy();
      counter.destroy(err);
      return;
    }
    hasher.update(chunk);
    counter.push(chunk);
  });
  source.on('end', () => {
    if (!failed.error) counter.push(null);
  });
  source.on('error', (err) => {
    failed.error = err;
    counter.destroy(err);
  });

  const handle = fs.createWriteStream(target, { mode: 0o600 });
  try {
    await pipeline(counter, handle);
  } catch (err) {
    await fsp.rm(target, { force: true }).catch(() => undefined);
    if (failed.error) throw failed.error;
    throw err instanceof Error ? err : new Error(String(err));
  }

  if (failed.error) {
    await fsp.rm(target, { force: true }).catch(() => undefined);
    throw failed.error;
  }

  return { storageKey, size, hash: hasher.digest() };
}

/** Write an in-memory buffer (used for avatars, which are small). */
export async function writeBuffer(data: Buffer): Promise<StoredBlob> {
  const storageKey = newStorageKey();
  const target = resolveSafe(storageKey);
  await fsp.mkdir(path.dirname(target), { recursive: true, mode: 0o700 });
  await fsp.writeFile(target, data, { mode: 0o600 });
  return {
    storageKey,
    size: data.length,
    hash: crypto.createHash('sha256').update(data).digest(),
  };
}

export function readBlobStream(storageKey: string): Readable {
  return fs.createReadStream(resolveSafe(storageKey));
}

export async function readBlob(storageKey: string): Promise<Buffer> {
  return fsp.readFile(resolveSafe(storageKey));
}

export async function blobExists(storageKey: string): Promise<boolean> {
  try {
    await fsp.access(resolveSafe(storageKey));
    return true;
  } catch {
    return false;
  }
}

export async function deleteBlob(storageKey: string): Promise<void> {
  try {
    await fsp.rm(resolveSafe(storageKey), { force: true });
  } catch (err) {
    logger.warn({ err }, 'failed to delete blob');
  }
}

export async function deleteBlobs(storageKeys: string[]): Promise<void> {
  await Promise.all(storageKeys.map((key) => deleteBlob(key)));
}
